"""Article lifecycle statuses and helpers."""

DRAFT = "DRAFT"
REVISION_REQUESTED = "REVISION_REQUESTED"
AWAITING_APPROVAL = "AWAITING_APPROVAL"
APPROVED = "APPROVED"
PUBLISHED = "PUBLISHED"
FAILED = "FAILED"
ARCHIVED = "ARCHIVED"

# Backward compatibility with old label used by prior API clients.
REJECTED = "REJECTED"

ALL_ARTICLE_STATUSES = {
    DRAFT,
    REVISION_REQUESTED,
    AWAITING_APPROVAL,
    APPROVED,
    PUBLISHED,
    FAILED,
    ARCHIVED,
    REJECTED,
}
